-- Movidos | Módulo de Funcionários
-- Execute uma única vez no SQL Editor do Supabase, após os scripts anteriores.
-- Esta tabela contém dados pessoais, trabalhistas e financeiros: acesso somente para administradores.

create table if not exists public.employees (
  id uuid primary key default gen_random_uuid(),
  employee_number bigint generated by default as identity unique,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  access_role text not null default 'operador' check (access_role in ('operador', 'financeiro')),
  employment_status text not null default 'ativo' check (employment_status in ('ativo', 'inativo', 'desligado')),

  full_name text not null,
  social_name text,
  birth_date date,
  gender text,
  marital_status text,
  nationality text,
  birthplace text,
  education_level text,
  mother_name text,
  father_name text,
  cpf text not null unique check (cpf ~ '^[0-9]{11}$'),
  rg_number text,
  rg_issuer text,
  rg_issue_date date,
  pis_pasep text,
  ctps_number text,
  ctps_series text,
  voter_registration text,

  address text,
  address_number text,
  address_complement text,
  neighborhood text,
  municipality text,
  state text check (state is null or state ~ '^[A-Z]{2}$'),
  postal_code text,
  mobile_phone text,
  emergency_phone text,
  personal_email citext not null unique,

  admission_date date,
  job_title text,
  department text,
  monthly_hours numeric(7,2),
  work_shift text,
  work_location text,
  bank_name text,
  bank_branch text,
  bank_account text,
  pix_key text,
  transport_voucher boolean not null default false,

  created_by uuid references public.user_profiles(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.employee_dependents (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.employees(id) on delete cascade,
  full_name text not null,
  cpf text check (cpf is null or cpf ~ '^[0-9]{11}$'),
  birth_date date,
  relationship text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_employees_name on public.employees (full_name);
create index if not exists idx_employees_department on public.employees (department);
create index if not exists idx_employee_dependents_employee on public.employee_dependents (employee_id);

drop trigger if exists employees_updated_at on public.employees;
create trigger employees_updated_at before update on public.employees
for each row execute function public.set_updated_at();

drop trigger if exists employee_dependents_updated_at on public.employee_dependents;
create trigger employee_dependents_updated_at before update on public.employee_dependents
for each row execute function public.set_updated_at();

-- Registra somente os campos alterados; nunca valores de CPF, documentos ou conta bancária.
create or replace function public.audit_employee_change() returns trigger
language plpgsql security definer set search_path = public as $$
declare changed_fields text[];
begin
  if tg_op = 'INSERT' then
    insert into public.audit_logs(user_id, action, entity_type, entity_id, details)
    values (auth.uid(), 'criado', 'employee', new.id, jsonb_build_object('employee_number', new.employee_number));
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.audit_logs(user_id, action, entity_type, entity_id, details)
    values (auth.uid(), 'excluido', 'employee', old.id, jsonb_build_object('employee_number', old.employee_number));
    return old;
  end if;

  select array_agg(key) into changed_fields
  from jsonb_each(to_jsonb(new)) as n(key, value)
  join jsonb_each(to_jsonb(old)) as o(key, value) using (key)
  where n.value is distinct from o.value
    and key not in ('updated_at', 'cpf', 'rg_number', 'pis_pasep', 'ctps_number', 'bank_account', 'pix_key');
  insert into public.audit_logs(user_id, action, entity_type, entity_id, details)
  values (auth.uid(), 'atualizado', 'employee', new.id, jsonb_build_object('fields', coalesce(to_jsonb(changed_fields), '[]'::jsonb)));
  return new;
end;
$$;

drop trigger if exists employees_audit on public.employees;
create trigger employees_audit after insert or update or delete on public.employees
for each row execute function public.audit_employee_change();

alter table public.employees enable row level security;
alter table public.employee_dependents enable row level security;

drop policy if exists "employees_admin_only" on public.employees;
create policy "employees_admin_only" on public.employees for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "employee_dependents_admin_only" on public.employee_dependents;
create policy "employee_dependents_admin_only" on public.employee_dependents for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Ao criar uma conta, vincula-a automaticamente ao funcionário com o mesmo e-mail.
-- Também aplica a permissão escolhida por RH para essa pessoa.
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
declare employee_role text;
begin
  insert into public.user_profiles (id, email, full_name)
  values (new.id, coalesce(new.email, new.id::text || '@invalid.local'), coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do nothing;

  update public.employees
  set auth_user_id = new.id
  where auth_user_id is null and lower(personal_email::text) = lower(coalesce(new.email, ''))
  returning access_role into employee_role;

  if employee_role is not null then
    update public.user_profiles set role = employee_role where id = new.id;
  end if;
  return new;
end;
$$;
