import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { hasSupabaseConfig, supabase } from './lib/supabase'
import type { Drop } from './lib/types'

const statuses = ['INTERESSADO','PICKUP - INTERESSADO','AG. ASSINATURA','CONTRATO ASSINADO','ENVIADO - AG. APROVAÇÃO','ATIVO','ATIVO - AG. LOGIN','ATIVO - AG. INSUMOS','CONGELADO','PROBLEMA','EXCLUÍDO']
const times = Array.from({length: 26}, (_, i) => `${String(Math.floor((480 + i * 30) / 60)).padStart(2,'0')}:${String((480 + i * 30) % 60).padStart(2,'0')}`)
const ufs = ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO']

function Login({onAuthenticated}:{onAuthenticated:()=>void}) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [signup,setSignup]=useState(false); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false)
  const submit=async(event:FormEvent)=>{event.preventDefault(); if(!supabase)return; setLoading(true);setMessage(''); const result=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setLoading(false);if(result.error){setMessage(result.error.message);return}if(signup){setMessage('Conta criada. Confirme o e-mail e entre no sistema.');return}onAuthenticated()}
  return <main className="auth-page"><section className="auth-hero"><p className="eyebrow">SISTEMA MOVIDOS</p><h1>Sistema<br/><em>Movidos.</em></h1><p>Operação integrada.</p></section><section className="auth-panel"><div className="brand-mark"><img src="/brand/movidos-fish.png" alt="Movidos"/></div><h2>{signup?'Criar acesso':'Sistema Movidos'}</h2><p>{hasSupabaseConfig?'Acesse sua conta.':'Faltam as variáveis públicas do Supabase neste ambiente.'}</p><form onSubmit={submit}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com" required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></label>{message&&<p className="form-message">{message}</p>}<button className="primary" disabled={!hasSupabaseConfig||loading}>{loading?'Aguarde…':signup?'Criar conta':'Entrar no sistema'}</button></form><button className="link-button" onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'Já tenho acesso':'Primeiro acesso? Criar conta'}</button></section></main>
}

function Layout({children,onSignOut}:{children:React.ReactNode;onSignOut:()=>void}){
  const nav=useNavigate(),loc=useLocation(),[open,setOpen]=useState(loc.pathname.startsWith('/cadastros')); const title=loc.pathname==='/'?'Visão geral':loc.pathname==='/cadastros'?'Cadastros':loc.pathname==='/cadastros/novo'?'Novo cadastro':loc.pathname.slice(1)
  return <div className="app"><aside><div className="side-brand"><img className="side-logo" src="/brand/movidos-fish.png" alt="Movidos"/><span>SISTEMA<br/><small>MOVIDOS</small></span></div><nav><button className={loc.pathname==='/'?'active':''} onClick={()=>nav('/')}>Visão geral</button><button className={loc.pathname.startsWith('/cadastros')?'active nav-parent':'nav-parent'} onClick={()=>setOpen(!open)}>Cadastros <span>{open?'−':'+'}</span></button>{open&&<div className="nav-submenu"><button className={loc.pathname==='/cadastros'?'sub-active':''} onClick={()=>nav('/cadastros')}>Ver cadastros</button><button className={loc.pathname==='/cadastros/novo'?'sub-active':''} onClick={()=>nav('/cadastros/novo')}>+ Novo cadastro</button></div>}<button onClick={()=>nav('/financeiro')}>Financeiro</button><button onClick={()=>nav('/extravios')}>Extravios</button><button onClick={()=>nav('/documentos')}>Documentos</button></nav><div className="side-bottom"><button className="link-button" onClick={onSignOut}>Sair</button></div></aside><main className="content"><header><div><p className="eyebrow">SISTEMA MOVIDOS</p><h1>{title}</h1></div></header>{children}</main></div>
}

function Field({label,children}:{label:string;children?:React.ReactNode}){return <label>{label}{children??<input/>}</label>}

function useDrops(){
  const [drops,setDrops]=useState<Drop[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const refresh=async()=>{if(!supabase){setLoading(false);return}setLoading(true);const {data,error:requestError}=await supabase.from('drops').select('id,legacy_id,name,partner,responsible,status,phone,email,municipality,state,zone,address,postal_code,monthly_value,created_at').order('legacy_id',{ascending:false}).range(0,1999);if(requestError)setError(requestError.message);else{setDrops((data??[]) as Drop[]);setError('')}setLoading(false)}
  useEffect(()=>{void refresh()},[]);return {drops,loading,error,refresh}
}

function Home(){const {drops,loading,error}=useDrops();const active=drops.filter(d=>d.status.startsWith('ATIVO')).length;const ongoing=drops.filter(d=>['INTERESSADO','PICKUP - INTERESSADO','AG. ASSINATURA','CONTRATO ASSINADO','ENVIADO - AG. APROVAÇÃO'].includes(d.status)).length;const issues=drops.filter(d=>['PROBLEMA','CONGELADO'].includes(d.status)).length;return <><section className="metric-grid"><article className="metric"><span>Drops cadastrados</span><strong>{loading?'…':drops.length}</strong></article><article className="metric green"><span>Ativos</span><strong>{loading?'…':active}</strong></article><article className="metric yellow"><span>Em andamento</span><strong>{loading?'…':ongoing}</strong></article><article className="metric red"><span>Problemas / congelados</span><strong>{loading?'…':issues}</strong></article></section>{error?<section className="card error-card"><strong>Não foi possível carregar a base.</strong><p>{error}</p></section>:<section className="card"><h2>Base operacional</h2><p>{loading?'Consultando o Supabase…':`${drops.length} cadastros reais carregados da base Movidos.`}</p></section>}</>}

function Lista(){
  const nav=useNavigate(),{drops,loading,error,refresh}=useDrops();const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[partner,setPartner]=useState(''),[zone,setZone]=useState('');const partners=useMemo(()=>[...new Set(drops.map(d=>d.partner).filter(Boolean) as string[])].sort(),[drops]);const zones=useMemo(()=>[...new Set(drops.map(d=>d.zone).filter(Boolean) as string[])].sort(),[drops]);const result=useMemo(()=>drops.filter(d=>{const text=[d.legacy_id,d.name,d.partner,d.responsible,d.phone,d.address,d.municipality,d.state,d.zone].join(' ').toLowerCase();return(!query||text.includes(query.toLowerCase()))&&(!status||d.status===status)&&(!partner||d.partner===partner)&&(!zone||d.zone===zone)}),[drops,query,status,partner,zone])
  return <><section className="card filter-card"><div className="filter-title"><div><p className="eyebrow">FILTROS</p><h2>Localize um cadastro</h2></div><button className="secondary" onClick={()=>{setQuery('');setStatus('');setPartner('');setZone('')}}>Limpar filtros</button></div><div className="filter-grid"><Field label="Busca"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ID, Drop, responsável, endereço…"/></Field><Field label="Status"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Parceiro"><select value={partner} onChange={e=>setPartner(e.target.value)}><option value="">Todos</option>{partners.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Zona"><select value={zone} onChange={e=>setZone(e.target.value)}><option value="">Todas</option>{zones.map(x=><option key={x}>{x}</option>)}</select></Field></div></section>{error&&<section className="card error-card"><strong>Erro ao carregar os cadastros.</strong><p>{error}</p></section>}<section className="toolbar"><p className="result-count">{loading?'Carregando cadastros…':`${result.length} cadastro(s) encontrado(s)`}</p><div><button className="secondary" onClick={()=>void refresh()}>Atualizar</button><button className="primary compact" onClick={()=>nav('/cadastros/novo')}>+ Novo cadastro</button></div></section><section className="card"><div className="table-wrap"><table><thead><tr><th>ID</th><th>Status</th><th>Drop</th><th>Parceiro</th><th>Responsável</th><th>Telefone</th><th>Logradouro</th><th>Zona</th><th>Ações</th></tr></thead><tbody>{result.map(d=><tr key={d.id}><td>{d.legacy_id??'—'}</td><td><span className="pill ativo">{d.status}</span></td><td><strong>{d.name}</strong></td><td>{d.partner??'—'}</td><td>{d.responsible??'—'}</td><td>{d.phone??'—'}</td><td>{d.address??'—'}</td><td>{d.zone??'—'}</td><td className="action-cell"><button className="table-action" onClick={()=>nav(`/cadastros/novo?edit=${d.id}`)}>Editar</button></td></tr>)}</tbody></table></div></section></>
}

function TimeField({label}:{label:string}){return <Field label={label}><select><option>Selecionar</option>{times.map(t=><option key={t}>{t}</option>)}</select></Field>}
function Novo(){const nav=useNavigate();return <section className="cadastro-form"><section className="form-section"><h3>Dados do ponto de coleta</h3><div className="form-grid"><Field label="ID"><input disabled placeholder="Gerado automaticamente"/></Field><Field label="Status"><select>{statuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Nome do Drop"/><Field label="Parceiro logístico"/><Field label="Responsável"/><Field label="Logradouro"/><Field label="Número"/><Field label="Complemento"/><Field label="Bairro"/><Field label="CEP"/><Field label="Município"/><Field label="UF"><select><option>Selecionar</option>{ufs.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Telefone"/><Field label="E-mail"><input type="email"/></Field><Field label="Latitude"/><Field label="Longitude"/><Field label="CPF"/><Field label="Valor acordado (R$)"/><Field label="Chave PIX"/><Field label="Nome PIX"/><Field label="Zona / Região"/><Field label="Tamanho (m²)"/></div></section><section className="form-section"><h3>Dados empresariais</h3><div className="form-grid"><Field label="CNPJ"/><Field label="IE"/><Field label="Nome empresarial"/><Field label="Nome fantasia"/></div></section><section className="form-section"><h3>Horário de operação</h3><div className="form-grid"><TimeField label="Abertura semanal"/><TimeField label="Fechamento semanal"/><TimeField label="Abertura sábado"/><TimeField label="Fechamento sábado"/><TimeField label="Horário bipagem semanal"/><TimeField label="Horário bipagem sábado"/><label className="full">Anotações<textarea/></label></div></section><div className="modal-actions"><button onClick={()=>nav('/cadastros')}>Cancelar</button><button className="primary compact">Salvar cadastro</button></div></section>}
function Empty({title}:{title:string}){return <section className="empty-state"><span>PRÓXIMA ETAPA</span><h2>{title}</h2><p>O banco legado já foi migrado. Este módulo será ligado à nova base em seguida.</p></section>}

function ProtectedApp(){const [logged,setLogged]=useState(false),[checking,setChecking]=useState(true);useEffect(()=>{if(!supabase){setChecking(false);return}supabase.auth.getSession().then(({data})=>{setLogged(Boolean(data.session));setChecking(false)});const {data:listener}=supabase.auth.onAuthStateChange((_event,session)=>setLogged(Boolean(session)));return()=>listener.subscription.unsubscribe()},[]);const exit=async()=>{await supabase?.auth.signOut();setLogged(false)};if(checking)return <main className="auth-page"><p>Verificando acesso…</p></main>;if(!logged)return <Login onAuthenticated={()=>setLogged(true)}/>;return <Layout onSignOut={()=>void exit()}><Routes><Route path="/" element={<Home/>}/><Route path="/cadastros" element={<Lista/>}/><Route path="/cadastros/novo" element={<Novo/>}/><Route path="/financeiro" element={<Empty title="Financeiro"/>}/><Route path="/extravios" element={<Empty title="Extravios"/>}/><Route path="/documentos" element={<Empty title="Documentos"/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></Layout>}
export default function App(){return <ProtectedApp/>}
