// @ts-nocheck
import {useEffect,useMemo,useRef,useState} from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import type { Drop } from './lib/types'
const statusTone=(status:string)=>{if(status.startsWith('ATIVO'))return 'active';if(status.includes('PROBLEMA')||status.includes('EXCLU'))return 'problem';if(status.includes('CONGELADO'))return 'frozen';return 'progress'}
const statusColor:Record<string,string>={active:'#008b89',progress:'#237be7',frozen:'#7556c7',problem:'#d94b44'}
const mapLocation=(drop:Drop)=>drop.latitude!==null&&drop.longitude!==null&&Number(drop.latitude)>=-35&&Number(drop.latitude)<=6&&Number(drop.longitude)>=-75&&Number(drop.longitude)<=-32
const searchText=(value:unknown)=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()
export default function DropMap({drops}:{drops:Drop[]}){const holder=useRef<HTMLDivElement>(null);const[city,setCity]=useState('');const points=useMemo(()=>drops.filter(mapLocation),[drops]);const cities=useMemo(()=>[...new Set(points.map(d=>String(d.municipality??'')).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')),[points]);const filtered=useMemo(()=>{const term=searchText(city);return term?points.filter(d=>searchText(d.municipality).includes(term)):points},[points,city]);useEffect(()=>{if(!holder.current)return;const map=L.map(holder.current,{scrollWheelZoom:true}).setView([-14.235,-51.925],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(map);const bounds:L.LatLngExpression[]=[];filtered.forEach(d=>{const point:[number,number]=[Number(d.latitude),Number(d.longitude)];bounds.push(point);const color=statusColor[statusTone(d.status)];const popup=document.createElement('div');const name=document.createElement('strong');name.textContent=d.name;const place=document.createElement('div');place.textContent=[d.municipality,d.state].filter(Boolean).join(' ');const status=document.createElement('small');status.textContent=d.status;popup.append(name,place,status);L.circleMarker(point,{radius:7,color,fillColor:color,fillOpacity:.88,weight:2}).addTo(map).bindPopup(popup)});if(bounds.length)map.fitBounds(bounds,{padding:[32,32],maxZoom:12});return()=>{map.remove()}},[filtered]);return <section className="card map-card"><div className="map-heading"><div><p className="eyebrow">MAPA OPERACIONAL</p><h2>Pontos de coleta</h2></div><span>{filtered.length} localizacoes exibidas</span></div><div className="map-controls"><label>Filtrar por cidade<input list="cities-map" value={city} onChange={e=>setCity(e.target.value)} placeholder="Digite o municipio"/></label><button type="button" className="secondary" onClick={()=>setCity('')}>Limpar mapa</button><datalist id="cities-map">{cities.map(item=><option key={item} value={item}/>)}</datalist></div><div className="map-legend"><span><i className="status-dot status-active"/>Ativo</span><span><i className="status-dot status-progress"/>Em andamento</span><span><i className="status-dot status-frozen"/>Congelado</span><span><i className="status-dot status-problem"/>Problema / excluido</span><small>Use a roda do mouse para ampliar ou reduzir.</small></div><div className="drops-map" ref={holder}/></section>}
