// @ts-nocheck
import { useEffect, useMemo, useState } from 'react'
import { supabase } from './lib/supabase'

type Kind = 'total' | 'details' | 'losses'
const money = (value: unknown) => Number(value ?? 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
const number = (value: unknown) => Number(value ?? 0) || 0
const key = (value: unknown) => String(value ?? '').trim().toLocaleUpperCase('pt-BR')
const periodOrder = (label: string) => Number(String(label).match(/^\s*(\d+)/)?.[1] ?? 0)
const lossType = (status: unknown) => { const value = key(status); return value.includes('W2D') ? 'w2d' : value.includes('D2D') ? 'd2d' : 'other' }
const date = (value: unknown) => { if (!value) return '—'; const text = String(value); const parsed = new Date(/^\d{4}-\d{2}-\d{2}$/.test(text) ? `${text}T12:00:00` : text); return Number.isNaN(parsed.getTime()) ? '—' : parsed.toLocaleDateString('pt-BR') }
async function allRows(table: string, columns = '*') { if (!supabase) return []; const rows: any[] = []; for (let from = 0; ; from += 1000) { const { data, error } = await supabase.from(table).select(columns).range(from, from + 999); if (error) throw error; rows.push(...(data ?? [])); if ((data ?? []).length < 1000) return rows } }

export default function FinanceiroVisuais({ kind }: { kind: Kind }) {
  const [periods, setPeriods] = useState<any[]>([]), [history, setHistory] = useState<any[]>([]), [items, setItems] = useState<any[]>([]), [losses, setLosses] = useState<any[]>([])
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [periodFilter, setPeriodFilter] = useState(''), [partnerFilter, setPartnerFilter] = useState(''), [statusFilter, setStatusFilter] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const [periodRows, historyRows, itemRows, lossRows] = await Promise.all([allRows('financial_periods', 'id,label,partner,payment_date,net_amount,status'), allRows('financial_payment_history'), allRows('financial_drop_items', 'id,financial_period_id,drop_name_snapshot,quantity_packages,unit_value,reimbursement'), allRows('loss_events')]); setPeriods(periodRows); setHistory(historyRows); setItems(itemRows); setLosses(lossRows) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível carregar os dados financeiros.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const periodById = useMemo(() => new Map(periods.map(row => [row.id, row])), [periods])
  const lossByDetail = useMemo(() => { const result = new Map<string, any>(); losses.forEach(loss => { const identity = `${loss.financial_period_id ?? key(loss.period_label)}|${key(loss.drop_name_snapshot)}`, current = result.get(identity) ?? { w2d: 0, d2d: 0, other: 0 }; current[lossType(loss.status)] += number(loss.amount); result.set(identity, current) }); return result }, [losses])
  const details = useMemo(() => {
    const source = history.length ? history.map(row => { const period = periodById.get(row.financial_period_id), split = lossByDetail.get(`${row.financial_period_id ?? key(row.period_label)}|${key(row.drop_name_snapshot)}`) ?? { w2d: 0, d2d: 0, other: 0 }, totalLoss = number(row.loss_amount); return { id: row.id, period: row.period_label ?? period?.label ?? 'Sem período', partner: row.partner ?? period?.partner ?? '—', drop: row.drop_name_snapshot ?? '—', responsible: row.responsible, packages: number(row.package_quantity), unit: number(row.amount), subtotal: number(row.subtotal), w2d: split.w2d, d2d: split.d2d, other: Math.max(0, totalLoss - split.w2d - split.d2d), loss: totalLoss, reimbursement: number(row.reimbursement), receivable: number(row.total_receivable), paymentDate: row.paid_at ?? period?.payment_date, pix: row.pix_key } }) : items.map(row => { const period = periodById.get(row.financial_period_id), split = lossByDetail.get(`${row.financial_period_id}|${key(row.drop_name_snapshot)}`) ?? { w2d: 0, d2d: 0, other: 0 }, subtotal = number(row.quantity_packages) * number(row.unit_value), loss = split.w2d + split.d2d + split.other; return { id: row.id, period: period?.label ?? 'Sem período', partner: period?.partner ?? '—', drop: row.drop_name_snapshot, packages: number(row.quantity_packages), unit: number(row.unit_value), subtotal, ...split, loss, reimbursement: number(row.reimbursement), receivable: subtotal - loss + number(row.reimbursement), paymentDate: period?.payment_date } }); return source.sort((a, b) => periodOrder(a.period) - periodOrder(b.period) || a.partner.localeCompare(b.partner) || a.drop.localeCompare(b.drop))
  }, [history, items, periodById, lossByDetail])
  const periodOptions = useMemo(() => [...new Set([...periods.map(row => row.label), ...details.map(row => row.period)])].filter(Boolean).sort((a, b) => periodOrder(a) - periodOrder(b)), [periods, details])
  const partnerOptions = useMemo(() => [...new Set(details.map(row => row.partner).filter(Boolean))].sort(), [details])
  const filteredDetails = useMemo(() => details.filter(row => (!periodFilter || row.period === periodFilter) && (!partnerFilter || row.partner === partnerFilter)), [details, periodFilter, partnerFilter])
  const totals = useMemo(() => { const byPeriod = new Map<string, any>(), ensure = (label: string) => { if (!byPeriod.has(label)) byPeriod.set(label, { period: label, gross: 0, w2d: 0, d2d: 0, other: 0, reimbursement: 0, payable: 0, net: 0, paymentDate: null }); return byPeriod.get(label) }; periods.forEach(row => { const total = ensure(row.label); total.net += number(row.net_amount); total.paymentDate = total.paymentDate ?? row.payment_date }); filteredDetails.forEach(row => { const total = ensure(row.period); total.gross += row.subtotal; total.w2d += row.w2d; total.d2d += row.d2d; total.other += row.other; total.reimbursement += row.reimbursement; total.payable += row.receivable; total.paymentDate = total.paymentDate ?? row.paymentDate }); return [...byPeriod.values()].filter(row => !periodFilter || row.period === periodFilter).sort((a, b) => periodOrder(a.period) - periodOrder(b.period)).map(row => { const calculatedNet = row.gross - row.w2d - row.d2d - row.other + row.reimbursement; const net = row.net || calculatedNet; return { ...row, loss: row.w2d + row.d2d + row.other, net, companyPayment: net - row.payable } }) }, [periods, filteredDetails, periodFilter])
  const filteredLosses = useMemo(() => losses.filter(row => { const period = row.period_label ?? periodById.get(row.financial_period_id)?.label, partner = row.partner ?? periodById.get(row.financial_period_id)?.partner; return (!periodFilter || period === periodFilter) && (!partnerFilter || partner === partnerFilter) && (!statusFilter || row.status === statusFilter) }).sort((a, b) => String(b.received_at ?? '').localeCompare(String(a.received_at ?? ''))), [losses, periodById, periodFilter, partnerFilter, statusFilter])
  const lossStatusOptions = useMemo(() => [...new Set(losses.map(row => row.status).filter(Boolean))].sort(), [losses])
  const title = kind === 'total' ? 'Pagamento Total' : kind === 'details' ? 'Pagamento Detalhes' : 'Extravios', description = kind === 'total' ? 'Consolidado automático por período, calculado a partir da base financeira.' : kind === 'details' ? 'Fechamento por DROP com valores, extravios e total a receber.' : 'Ocorrências de extravio importadas, com rastreabilidade por DROP.'
  return <section className="finance-visual-page"><section className="card visual-heading"><div><p className="eyebrow">FINANCEIRO</p><h2>{title}</h2><p>{description}</p></div><button className="secondary" onClick={() => void load()} disabled={loading}>{loading ? 'Atualizando…' : 'Atualizar dados'}</button></section><section className="card visual-filters"><label>Período<select value={periodFilter} onChange={event => setPeriodFilter(event.target.value)}><option value="">Todos os períodos</option>{periodOptions.map(value => <option key={value}>{value}</option>)}</select></label><label>Parceiro<select value={partnerFilter} onChange={event => setPartnerFilter(event.target.value)}><option value="">Todos os parceiros</option>{partnerOptions.map(value => <option key={value}>{value}</option>)}</select></label>{kind === 'losses' && <label>Status<select value={statusFilter} onChange={event => setStatusFilter(event.target.value)}><option value="">Todos os status</option>{lossStatusOptions.map(value => <option key={value}>{value}</option>)}</select></label>}</section>{error && <p className="error">{error}</p>}{loading ? <section className="card empty">Carregando dados da base…</section> : kind === 'total' ? <PaymentTotal rows={totals} /> : kind === 'details' ? <PaymentDetails rows={filteredDetails} /> : <Losses rows={filteredLosses} periodById={periodById} />}</section>
}
function PaymentTotal({ rows }: any) { return <section className="card"><div className="table-wrap"><table><thead><tr><th>Período</th><th>Valor bruto a receber</th><th>Extravio W2D</th><th>Extravio D2D</th><th>Total de extravios</th><th>Reembolso iMile</th><th>Total líquido a receber</th><th>Pagamento aos DROPs</th><th>Pagamento empresa</th><th>Data do pagamento</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.period}><td><strong>{row.period}</strong></td><td>{money(row.gross)}</td><td>{money(row.w2d)}</td><td>{money(row.d2d)}</td><td className="loss-value">{money(row.loss)}</td><td>{money(row.reimbursement)}</td><td><strong>{money(row.net)}</strong></td><td>{money(row.payable)}</td><td className={row.companyPayment < 0 ? 'loss-value' : 'positive-value'}>{money(row.companyPayment)}</td><td>{date(row.paymentDate)}</td></tr>)}{!rows.length && <tr><td colSpan={10} className="empty">Nenhum pagamento encontrado para os filtros selecionados.</td></tr>}</tbody></table></div></section> }
function PaymentDetails({ rows }: any) { return <section className="card"><div className="table-wrap"><table><thead><tr><th>Período</th><th>DROP</th><th>Parceiro</th><th>Total pacote</th><th>Valor acordado</th><th>Subtotal</th><th>Extravio W2D</th><th>Extravio D2D</th><th>Total extravio</th><th>Reembolso</th><th>Total a receber</th><th>Data pagamento</th><th>PIX</th></tr></thead><tbody>{rows.map((row: any) => <tr key={row.id}><td>{row.period}</td><td><strong>{row.drop}</strong>{row.responsible && <small className="table-subtitle">{row.responsible}</small>}</td><td>{row.partner}</td><td>{row.packages.toLocaleString('pt-BR')}</td><td>{money(row.unit)}</td><td>{money(row.subtotal)}</td><td>{money(row.w2d)}</td><td>{money(row.d2d)}</td><td className="loss-value">{money(row.loss)}</td><td>{money(row.reimbursement)}</td><td className="positive-value">{money(row.receivable)}</td><td>{date(row.paymentDate)}</td><td>{row.pix ?? '—'}</td></tr>)}{!rows.length && <tr><td colSpan={13} className="empty">Nenhum DROP encontrado para os filtros selecionados.</td></tr>}</tbody></table></div></section> }
function Losses({ rows, periodById }: any) { return <section className="card"><div className="table-wrap"><table><thead><tr><th>Período</th><th>Scan station / DROP</th><th>Waybill nº</th><th>Código da etiqueta</th><th>Saca</th><th>Status</th><th>Seller</th><th>Recebimento</th><th>Valor</th><th>Observações</th></tr></thead><tbody>{rows.map((row: any) => { const period = periodById.get(row.financial_period_id); return <tr key={row.id}><td>{row.period_label ?? period?.label ?? '—'}</td><td><strong>{row.drop_name_snapshot ?? '—'}</strong><small className="table-subtitle">{row.partner ?? period?.partner ?? ''}</small></td><td>{row.waybill ?? '—'}</td><td>{row.label_code ?? '—'}</td><td>{row.bag_code ?? '—'}</td><td><span className="pill">{row.status ?? '—'}</span></td><td>{row.seller ?? '—'}</td><td>{row.received_at ? new Date(row.received_at).toLocaleString('pt-BR') : '—'}</td><td className="loss-value">{money(row.amount)}</td><td>{row.observation ?? '—'}</td></tr> })}{!rows.length && <tr><td colSpan={10} className="empty">Nenhum extravio encontrado para os filtros selecionados.</td></tr>}</tbody></table></div></section> }
