// @ts-nocheck
import { ChangeEvent, useEffect, useMemo, useState } from 'react'
import * as XLSX from 'xlsx'
import { supabase } from './lib/supabase'

type Row = Record<string, unknown>
type View = { id:string; title:string; source_file_name:string; source_rows:number; import_status:string; created_at:string }
const text=(v:unknown)=>String(v??'').trim()
const number=(v:unknown)=>Number(String(v??0).replace(',','.'))||0
const required=(row:Row, columns:string[])=>columns.every(c=>text(row[c]))

export default function Financeiro(){
  const [views,setViews]=useState<View[]>([]),[selected,setSelected]=useState(''),[closing,setClosing]=useState<Row[]>([]),[losses,setLosses]=useState<Row[]>([]),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[details,setDetails]=useState<any[]>([]),[viewLosses,setViewLosses]=useState<any[]>([])
  const refresh=async()=>{if(!supabase)return;const{data,error}=await supabase.from('financial_views').select('*').order('created_at',{ascending:false});if(error){setMessage('Execute a migração financeira no Supabase antes de usar este módulo.');return}setViews(data??[])}
  useEffect(()=>{void refresh()},[])
  useEffect(()=>{if(!selected||!supabase)return;const load=async()=>{const {data:periods}=await supabase.from('financial_periods').select('id,label,partner,net_amount,status').eq('financial_view_id',selected);const ids=(periods??[]).map(x=>x.id);if(!ids.length){setDetails([]);setViewLosses([]);return}const [{data:items},{data:loss}]=await Promise.all([supabase.from('financial_drop_items').select('*').in('financial_period_id',ids).order('drop_name_snapshot'),supabase.from('loss_events').select('*').in('financial_period_id',ids).order('created_at')]);setDetails((items??[]).map(x=>({...x,period:(periods??[]).find(p=>p.id===x.financial_period_id)})));setViewLosses(loss??[])};void load()},[selected])
  const choose=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setMessage('');try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const closeSheet=workbook.Sheets['Fechamento'];const lossSheet=workbook.Sheets['Extravios'];if(!closeSheet||!lossSheet)throw new Error('Use o Modelo_Fechamento_Financeiro.xlsx, com as abas Fechamento e Extravios.');const close=XLSX.utils.sheet_to_json<Row>(closeSheet,{defval:''});const loss=XLSX.utils.sheet_to_json<Row>(lossSheet,{defval:''});const invalid=close.filter(x=>!required(x,['Periodo','Parceiro','Drop'])||number(x.QuantidadePacote)<0).length+loss.filter(x=>!required(x,['Periodo','Parceiro','Drop'])).length;setClosing(close);setLosses(loss);setTitle(file.name.replace(/\.[^.]+$/,''));setMessage(invalid?`${invalid} linha(s) precisam ser corrigidas antes da importação.`:`Prévia pronta: ${close.length} itens de fechamento e ${loss.length} extravios.`)}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível ler a planilha.')}}
  const invalid=useMemo(()=>closing.some(x=>!required(x,['Periodo','Parceiro','Drop'])||number(x.QuantidadePacote)<0)||losses.some(x=>!required(x,['Periodo','Parceiro','Drop'])),[closing,losses])
  const importView=async()=>{if(!supabase||!closing.length||invalid)return;setBusy(true);setMessage('Importando View...');try{const fileName=title+'.xlsx';const{data:view,error:viewError}=await supabase.from('financial_views').insert({title,source_file_name:fileName,source_rows:closing.length+losses.length,import_status:'rascunho'}).select().single();if(viewError)throw viewError;const groups=[...new Map(closing.map(x=>[`${text(x.Periodo)}|${text(x.Parceiro)}`,{label:text(x.Periodo),partner:text(x.Parceiro)}])).values()];const{data:periods,error:periodError}=await supabase.from('financial_periods').insert(groups.map(g=>({...g,financial_view_id:view.id,status:'aberto'}))).select();if(periodError)throw periodError;const index=new Map((periods??[]).map(p=>[`${p.label}|${p.partner}`,p.id]));const chunks=<T,>(rows:T[])=>Array.from({length:Math.ceil(rows.length/400)},(_,i)=>rows.slice(i*400,i*400+400));for(const part of chunks(closing)){const{error}=await supabase.from('financial_drop_items').insert(part.map(x=>({financial_period_id:index.get(`${text(x.Periodo)}|${text(x.Parceiro)}`),drop_name_snapshot:text(x.Drop),quantity_packages:number(x.QuantidadePacote),unit_value:0,reimbursement:0})));if(error)throw error}for(const part of chunks(losses)){const{error}=await supabase.from('loss_events').insert(part.map(x=>({financial_period_id:index.get(`${text(x.Periodo)}|${text(x.Parceiro)}`),partner:text(x.Parceiro),period_label:text(x.Periodo),drop_name_snapshot:text(x.Drop),waybill:text(x.Waybill),label_code:text(x.CodigoEtiqueta),bag_code:text(x.Saca),status:text(x.Status),seller:text(x.Seller),received_at:text(x.DataRecebimento)||null,amount:number(x.ValorExtravio),observation:text(x.Obs)})));if(error)throw error}await supabase.from('financial_views').update({import_status:'importado'}).eq('id',view.id);setClosing([]);setLosses([]);setSelected(view.id);setMessage('View importada com sucesso.');await refresh()}catch(error){setMessage(error instanceof Error?error.message:'Erro ao importar.')}finally{setBusy(false)}}
  const editLoss=async(loss:any)=>{if(!supabase)return;const amount=prompt('Valor do extravio (R$):',String(loss.amount??0));if(amount===null)return;const observation=prompt('Observação / motivo da alteração:',loss.observation??'');if(observation===null)return;const{error}=await supabase.from('loss_events').update({amount:number(amount),observation}).eq('id',loss.id);setMessage(error?error.message:'Extravio atualizado nesta View.');if(!error)setSelected('');setTimeout(()=>setSelected(views.find(v=>v.id===selected)?.id??''),0)}
  return <section className="finance-page"><section className="card finance-upload"><div><p className="eyebrow">FECHAMENTOS</p><h2>Nova View financeira</h2><p>Envie o modelo quinzenal. Cada arquivo cria uma versão independente.</p></div><a className="secondary" href="/templates/modelo-fechamento-financeiro.xlsx" download>Baixar modelo</a><label className="upload-button">Selecionar planilha<input type="file" accept=".xlsx" onChange={choose}/></label></section>{closing.length>0&&<section className="card finance-preview"><label>Nome da View<input value={title} onChange={e=>setTitle(e.target.value)}/></label><strong>{closing.length} itens · {losses.length} extravios</strong><button className="primary compact" disabled={busy||invalid} onClick={()=>void importView}>{busy?'Importando...':'Criar View'}</button></section>}{message&&<p className="form-message">{message}</p>}<section className="card"><div className="finance-head"><div><p className="eyebrow">VIEWS SALVAS</p><h2>Consultar fechamento</h2></div><button className="secondary" onClick={()=>void refresh()}>Atualizar</button></div><select className="view-select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecione uma View</option>{views.map(v=><option key={v.id} value={v.id}>{v.title} · {new Date(v.created_at).toLocaleString('pt-BR')}</option>)}</select></section>{selected&&<><section className="finance-summary"><article className="metric"><span>Itens por Drop</span><strong>{details.length}</strong></article><article className="metric red"><span>Extravios</span><strong>{viewLosses.length}</strong></article></section><section className="card"><h2>Itens da View</h2><div className="table-wrap"><table><thead><tr><th>Período</th><th>Parceiro</th><th>Drop</th><th>Pacotes</th><th>Valor unitário</th><th>Total</th></tr></thead><tbody>{details.map(x=><tr key={x.id}><td>{x.period?.label}</td><td>{x.period?.partner}</td><td>{x.drop_name_snapshot}</td><td>{x.quantity_packages}</td><td>R$ {Number(x.unit_value).toFixed(2)}</td><td>R$ {Number(x.total_amount).toFixed(2)}</td></tr>)}</tbody></table></div></section><section className="card"><h2>Extravios da View</h2><div className="table-wrap"><table><thead><tr><th>Drop</th><th>Waybill</th><th>Status</th><th>Valor</th><th>Observação</th><th>Ação</th></tr></thead><tbody>{viewLosses.map(x=><tr key={x.id}><td>{x.drop_name_snapshot}</td><td>{x.waybill}</td><td>{x.status}</td><td>R$ {Number(x.amount).toFixed(2)}</td><td>{x.observation}</td><td><button className="table-action" onClick={()=>void editLoss(x)}>Editar</button></td></tr>)}</tbody></table></div></section></>}</section>
}
